begin;

create schema if not exists anta_daily;

create or replace function anta_daily.format_pct(v numeric)
returns text
language sql
immutable
as $$
    select case
        when v is null then null
        else trim(to_char(round(v * 100.0, 2), 'FM999999990.00')) || '%'
    end
$$;

create or replace view anta_daily.v_rpt_daily_sku_wide_export_display as
select
    sales_date as "出库时间",
    style as "款号",
    sku as "货号",
    major_category as "大类",
    category as "中类",
    product_name as "品名",
    tag_price as "零售价",
    season as "年季",
    gender as "性别",
    story_pack as "故事包",
    coalesce(round(inv_huotong_qty), 0)::bigint as "库存_货通",
    coalesce(round(inv_women_qty), 0)::bigint as "库存_女子",
    coalesce(round(inv_outdoor_qty), 0)::bigint as "库存_户外",
    coalesce(round(inv_trend_qty), 0)::bigint as "库存_潮流",
    coalesce(round(inv_casual_qty), 0)::bigint as "库存_休闲",
    coalesce(round(inv_c_store_qty), 0)::bigint as "库存_C店",
    coalesce(round(inv_category_shared_qty), 0)::bigint as "库存_品类共享",
    coalesce(round(inv_tmall_outlet_qty), 0)::bigint as "库存_天猫奥莱",
    coalesce(round(inv_shared_qty), 0)::bigint as "库存_共享",
    coalesce(round(inv_tmall_flagship_qty), 0)::bigint as "库存_天猫旗舰",
    coalesce(round(inv_tmall_franchise_qty), 0)::bigint as "库存_天猫专卖",
    coalesce(round(inv_shanghai_franchise_qty), 0)::bigint as "库存_上海专卖",
    coalesce(round(inv_jd_flagship_qty), 0)::bigint as "库存_京东旗舰",
    coalesce(round(inv_jd_franchise_qty), 0)::bigint as "库存_京东专卖",
    coalesce(round(inv_jd_self_qty), 0)::bigint as "库存_京自营",
    coalesce(round(inv_dewu_qty), 0)::bigint as "库存_得物",
    coalesce(round(inv_interest_qty), 0)::bigint as "库存_兴趣",
    coalesce(round(inv_vip_qty), 0)::bigint as "库存_唯品",
    coalesce(round(inv_pdd_qty), 0)::bigint as "库存_拼多多",
    coalesce(round(inv_distributor_qty), 0)::bigint as "库存_经销",
    coalesce(round(inv_other_qty), 0)::bigint as "库存_其他",
    coalesce(round(inventory_total_qty), 0)::bigint as "全渠道库存",
    coalesce(round(sales_women_qty), 0)::bigint as "销售_女子",
    coalesce(round(sales_outdoor_qty), 0)::bigint as "销售_户外",
    coalesce(round(sales_trend_qty), 0)::bigint as "销售_潮流",
    coalesce(round(sales_casual_qty), 0)::bigint as "销售_休闲",
    coalesce(round(sales_tmall_badminton_qty), 0)::bigint as "销售_天猫羽球",
    coalesce(round(sales_tmall_outlet_qty), 0)::bigint as "销售_天猫奥莱",
    coalesce(round(sales_c_store_qty), 0)::bigint as "销售_C店",
    coalesce(round(sales_outlet_anjianli_qty), 0)::bigint as "销售_奥莱安建立",
    coalesce(round(sales_tmall_flagship_qty), 0)::bigint as "销售_天猫旗舰",
    coalesce(round(sales_tmall_franchise_qty), 0)::bigint as "销售_天猫专卖",
    coalesce(round(sales_shanghai_franchise_qty), 0)::bigint as "销售_上海专卖",
    coalesce(round(sales_jd_flagship_qty), 0)::bigint as "销售_京东旗舰",
    coalesce(round(sales_jd_franchise_qty), 0)::bigint as "销售_京东专卖",
    coalesce(round(sales_jd_self_qty), 0)::bigint as "销售_京自营",
    coalesce(round(sales_dewu_qty), 0)::bigint as "销售_得物",
    coalesce(round(sales_vip_qty), 0)::bigint as "销售_唯品",
    coalesce(round(sales_pdd_qty), 0)::bigint as "销售_拼多多",
    coalesce(round(sales_interest_qty), 0)::bigint as "销售_兴趣",
    coalesce(round(sales_official_qty), 0)::bigint as "销售_官网",
    coalesce(round(sales_group_buy_qty), 0)::bigint as "销售_团购",
    coalesce(round(sales_distributor_qty), 0)::bigint as "销售_经销",
    coalesce(round(sales_other_qty), 0)::bigint as "销售_其他",
    coalesce(round(sales_total_qty), 0)::bigint as "全渠道销售",
    anta_daily.format_pct(sku_discount_women) as "货号折扣_女子",
    anta_daily.format_pct(sku_discount_outdoor) as "货号折扣_户外",
    anta_daily.format_pct(sku_discount_trend) as "货号折扣_潮流",
    anta_daily.format_pct(sku_discount_casual) as "货号折扣_休闲",
    anta_daily.format_pct(sku_discount_tmall_badminton) as "货号折扣_天猫羽球",
    anta_daily.format_pct(sku_discount_tmall_outlet) as "货号折扣_天猫奥莱",
    anta_daily.format_pct(sku_discount_c_store) as "货号折扣_C店",
    anta_daily.format_pct(sku_discount_outlet_anjianli) as "货号折扣_奥莱安建立",
    anta_daily.format_pct(sku_discount_tmall_flagship) as "货号折扣_天猫旗舰",
    anta_daily.format_pct(sku_discount_tmall_franchise) as "货号折扣_天猫专卖",
    anta_daily.format_pct(sku_discount_shanghai_franchise) as "货号折扣_上海专卖",
    anta_daily.format_pct(sku_discount_jd_flagship) as "货号折扣_京东旗舰",
    anta_daily.format_pct(sku_discount_jd_franchise) as "货号折扣_京东专卖",
    anta_daily.format_pct(sku_discount_jd_self) as "货号折扣_京自营",
    anta_daily.format_pct(sku_discount_dewu) as "货号折扣_得物",
    anta_daily.format_pct(sku_discount_vip) as "货号折扣_唯品",
    anta_daily.format_pct(sku_discount_pdd) as "货号折扣_拼多多",
    anta_daily.format_pct(sku_discount_interest) as "货号折扣_兴趣",
    anta_daily.format_pct(sku_discount_official) as "货号折扣_官网",
    anta_daily.format_pct(sku_discount_group_buy) as "货号折扣_团购",
    anta_daily.format_pct(sku_discount_distributor) as "货号折扣_经销",
    anta_daily.format_pct(sku_discount_other) as "货号折扣_其他",
    anta_daily.format_pct(sku_discount_total) as "全渠道折扣_货号层级",
    anta_daily.format_pct(style_discount_women) as "款号折扣_女子",
    anta_daily.format_pct(style_discount_outdoor) as "款号折扣_户外",
    anta_daily.format_pct(style_discount_trend) as "款号折扣_潮流",
    anta_daily.format_pct(style_discount_casual) as "款号折扣_休闲",
    anta_daily.format_pct(style_discount_tmall_badminton) as "款号折扣_天猫羽球",
    anta_daily.format_pct(style_discount_tmall_outlet) as "款号折扣_天猫奥莱",
    anta_daily.format_pct(style_discount_c_store) as "款号折扣_C店",
    anta_daily.format_pct(style_discount_outlet_anjianli) as "款号折扣_奥莱安建立",
    anta_daily.format_pct(style_discount_tmall_flagship) as "款号折扣_天猫旗舰",
    anta_daily.format_pct(style_discount_tmall_franchise) as "款号折扣_天猫专卖",
    anta_daily.format_pct(style_discount_shanghai_franchise) as "款号折扣_上海专卖",
    anta_daily.format_pct(style_discount_jd_flagship) as "款号折扣_京东旗舰",
    anta_daily.format_pct(style_discount_jd_franchise) as "款号折扣_京东专卖",
    anta_daily.format_pct(style_discount_jd_self) as "款号折扣_京自营",
    anta_daily.format_pct(style_discount_dewu) as "款号折扣_得物",
    anta_daily.format_pct(style_discount_vip) as "款号折扣_唯品",
    anta_daily.format_pct(style_discount_pdd) as "款号折扣_拼多多",
    anta_daily.format_pct(style_discount_interest) as "款号折扣_兴趣",
    anta_daily.format_pct(style_discount_official) as "款号折扣_官网",
    anta_daily.format_pct(style_discount_group_buy) as "款号折扣_团购",
    anta_daily.format_pct(style_discount_distributor) as "款号折扣_经销",
    anta_daily.format_pct(style_discount_other) as "款号折扣_其他",
    anta_daily.format_pct(style_discount_total) as "全渠道折扣_款号层级"
from anta_daily.rpt_daily_sku_wide;

commit;
